const traitInputAttr = { placeholder: '例如：在这里输入文本' };

const grapesjsZhCn = {
  assetManager: {
    addButton: '添加图片',
    inputPlh: 'http://图片地址/示例.jpg',
    modalTitle: '选择图片',
    uploadTitle: '将文件拖到这里，或点击上传',
  },
  domComponents: {
    names: {
      '': '容器',
      wrapper: '页面主体',
      text: '文本',
      comment: '注释',
      image: '图片',
      video: '视频',
      label: '标签',
      link: '链接',
      map: '地图',
      tfoot: '表格页脚',
      tbody: '表格主体',
      thead: '表格表头',
      table: '表格',
      row: '表格行',
      cell: '表格单元格',
    },
  },
  deviceManager: {
    device: '设备',
    devices: {
      desktop: '桌面端',
      tablet: '平板',
      mobileLandscape: '手机横屏',
      mobilePortrait: '手机竖屏',
    },
  },
  panels: {
    buttons: {
      titles: {
        preview: '预览',
        fullscreen: '全屏',
        'sw-visibility': '查看组件',
        'export-template': '查看代码',
        'open-sm': '打开样式管理器',
        'open-tm': '设置',
        'open-layers': '打开图层管理',
        'open-blocks': '打开区块面板',
      },
    },
  },
  selectorManager: {
    label: '类名',
    selected: '当前选中',
    emptyState: '- 状态 -',
    states: {
      hover: '悬停',
      active: '点击',
      'nth-of-type(2n)': '奇偶项',
    },
  },
  styleManager: {
    empty: '请先选中一个元素，再使用样式管理器',
    layer: '图层',
    fileButton: '图片',
    sectors: {
      general: '常规',
      layout: '布局',
      typography: '排版',
      decorations: '装饰',
      extra: '附加',
      flex: '弹性布局',
      dimension: '尺寸',
    },
    properties: {
      'text-shadow-h': '水平',
      'text-shadow-v': '垂直',
      'text-shadow-blur': '模糊',
      'text-shadow-color': '颜色',
      'box-shadow-h': '水平',
      'box-shadow-v': '垂直',
      'box-shadow-blur': '模糊',
      'box-shadow-spread': '扩散',
      'box-shadow-color': '颜色',
      'box-shadow-type': '类型',
      'margin-top-sub': '上',
      'margin-right-sub': '右',
      'margin-bottom-sub': '下',
      'margin-left-sub': '左',
      'padding-top-sub': '上',
      'padding-right-sub': '右',
      'padding-bottom-sub': '下',
      'padding-left-sub': '左',
      'border-width-sub': '宽度',
      'border-style-sub': '样式',
      'border-color-sub': '颜色',
      'border-top-left-radius-sub': '左上',
      'border-top-right-radius-sub': '右上',
      'border-bottom-right-radius-sub': '右下',
      'border-bottom-left-radius-sub': '左下',
      'transform-rotate-x': '沿 X 旋转',
      'transform-rotate-y': '沿 Y 旋转',
      'transform-rotate-z': '沿 Z 旋转',
      'transform-scale-x': 'X 缩放',
      'transform-scale-y': 'Y 缩放',
      'transform-scale-z': 'Z 缩放',
      'transition-property-sub': '属性',
      'transition-duration-sub': '时长',
      'transition-timing-function-sub': '缓动',
      'background-image-sub': '图片',
      'background-repeat-sub': '重复',
      'background-position-sub': '位置',
      'background-attachment-sub': '附着',
      'background-size-sub': '尺寸',
    },
    options: {
      float: {
        none: '无',
        left: '左浮动',
        right: '右浮动',
      },
      position: {
        static: '静态',
        relative: '相对',
        absolute: '绝对',
        fixed: '固定',
      },
      display: {
        block: '块级',
        inline: '行内',
        'inline-block': '行内块',
        flex: '弹性',
        none: '隐藏',
      },
    },
  },
  traitManager: {
    empty: '请先选中一个元素，再编辑组件设置',
    label: '组件设置',
    traits: {
      attributes: {
        id: traitInputAttr,
        alt: traitInputAttr,
        title: traitInputAttr,
        href: { placeholder: '例如：https://example.com' },
      },
      options: {
        target: {
          false: '当前窗口',
          _blank: '新窗口',
        },
      },
    },
  },
  storageManager: {
    recover: '是否恢复未保存的修改？',
  },
};

export default grapesjsZhCn;
