import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('VisualCanvasPane source defines an isolated design surface around GrapesJS', async () => {
  const source = await readFile(new URL('./VisualCanvasPane.tsx', import.meta.url), 'utf8');

  assert.match(source, /data-visual-html-mode="design"/);
  assert.match(source, /grapesjs\.init/);
  assert.match(source, /avoidInlineStyle: false/);
  assert.match(source, /forceClass: false/);
  assert.match(source, /registerVisualHtmlComponentTypes/);
  assert.match(source, /registerVisualHtmlBlocks/);
  assert.match(source, /grapesjsZhCn/);
  assert.match(source, /locale: 'zh-CN'/);
  assert.match(source, /messagesAdd/);
  assert.match(source, /normalizeDesignCanvasHtml/);
  assert.match(source, /stripCanvasSecurityPolicyMeta/);
  assert.match(source, /http-equiv\\s\*=\\s\*\(\["'\]\)\?Content-Security-Policy/);
  assert.match(source, /extractRootCustomProperties/);
  assert.match(source, /inlineCustomPropertyReferences/);
  assert.match(source, /collectStyleMarkup/);
  assert.match(source, /restoreOriginalElementAttributes\(editor, originalElementSnapshots\)/);
  assert.match(source, /collectOriginalElementSnapshots/);
  assert.match(source, /component\.setClass\?\.\(className/);
  assert.match(source, /collectMissingStyleRecord/);
  assert.match(source, /readComponentInlineStyleRecord/);
  assert.match(source, /component\.addStyle\?\.\(missingStyle/);
  assert.match(source, /component\.addAttributes\?\.\(changedRestAttributes/);
  assert.match(source, /buildComponentByElementMap/);
  assert.match(source, /findCanvasElementByFingerprint/);
  assert.match(source, /injectRawCanvasStyles/);
  assert.match(source, /collectCanvasHeadMarkup/);
  assert.match(source, /rewriteCanvasHeadAssetUrls/);
  assert.match(source, /createCanvasStructureHtml/);
  assert.match(source, /logCanvasPerf/);
  assert.match(source, /const canvasHtml = normalizeDesignCanvasHtml\(fullHtml\);/);
  assert.match(source, /const rawStyleMarkup = collectStyleMarkup\(canvasHtml\);/);
  assert.match(source, /const canvasHeadMarkup = rewriteCanvasHeadAssetUrls\(\s*collectCanvasHeadMarkup\(canvasHtml\),\s*assetBaseUrl,\s*\);/);
  assert.match(source, /const canvasStructureHtml = createCanvasStructureHtml\(canvasHtml\);/);
  assert.doesNotMatch(source, /editor\.getWrapper\(\)\?\.components\(canvasHtml/);
  assert.match(source, /editor\.getWrapper\(\)\?\.components\(canvasStructureHtml/);
  assert.match(source, /asDocument: true/);
  assert.match(source, /allowScripts: true/);
  assert.match(source, /detectDocument: true/);
  assert.match(source, /editor\.on\('update'/);
  assert.match(source, /editor\.on\('component:styleUpdate', notifyStyleDirty\)/);
  assert.match(source, /onDirtyChange/);
  assert.match(source, /onEditorReady/);
  assert.match(source, /editor\.Panels\.getPanel\('options'\)/);
  assert.match(source, /optionsPanel\.set\('visible', false\)/);
});

test('VisualCanvasPane source owns editor lifecycle and reload wiring', async () => {
  const source = await readFile(new URL('./VisualCanvasPane.tsx', import.meta.url), 'utf8');

  assert.match(source, /editor\.destroy\(\)/);
  assert.match(source, /editor\.clearDirtyCount\(\)/);
  assert.match(source, /fullHtml/);
  assert.match(source, /onEditorReadyRef/);
  assert.match(source, /onDirtyChangeRef/);
  assert.match(source, /injectCanvasHeadMarkup\(editor, canvasHeadMarkup\)/);
  assert.match(source, /injectRawCanvasStyles\(editor, rawStyleMarkup\)/);
  assert.match(source, /lastHeadSyncRef/);
  assert.match(source, /headSyncKey/);
  assert.match(source, /hasSyncedCanvasHeadMarkup/);
  assert.match(source, /logCanvasPerf\('head-sync-skip'/);
  assert.match(source, /scheduleCanvasHeadMarkupSync/);
  assert.match(source, /canvas:frame:load:body/);
  assert.match(source, /\}, \[assetBaseUrl, fullHtml\]\)/);
  assert.doesNotMatch(source, /\}, \[fullHtml, onDirtyChange, onEditorReady\]\)/);
});

test('VisualCanvasPane source keeps hidden interaction nodes but disables non-visual editing by default', async () => {
  const source = await readFile(new URL('./VisualCanvasPane.tsx', import.meta.url), 'utf8');

  assert.doesNotMatch(source, /element\.remove\(\)/);
  assert.match(source, /disableNonVisualEditableCanvasComponents/);
  assert.match(source, /applyHiddenLayerEditing/);
  assert.match(source, /showHiddenLayers/);
  assert.match(source, /hiddenLayerFilter/);
  assert.match(source, /data-ccui-hidden-layer-edit-style/);
  assert.match(source, /ccui-hidden-layer-editing/);
  assert.match(source, /data-ccui-hidden-layer-preview/);
  assert.match(source, /data-ccui-hidden-layer-original-style/);
  assert.match(source, /data-ccui-hidden-layer-pass-through/);
  assert.match(source, /type HiddenLayerDisplayMode = 'block' \| 'flex' \| 'grid' \| 'inline-flex' \| 'table-row' \| 'table-header-group' \| 'table-row-group' \| 'table-footer-group' \| 'table-cell' \| 'list-item'/);
  assert.match(source, /type HiddenLayerReason = 'display-none' \| 'visibility-hidden' \| 'opacity-zero' \| 'zero-size' \| 'offscreen' \| 'ancestor-hidden'/);
  assert.match(source, /type HiddenLayerFilter = \{/);
  assert.match(source, /type HiddenLayerRecord = \{/);
  assert.match(source, /textQuery: string/);
  assert.match(source, /function getDirectHiddenLayerReason\(/);
  assert.match(source, /function hasDirectHiddenAncestor\(/);
  assert.match(source, /function classifyHiddenLayerElement\(/);
  assert.match(source, /const NON_VISUAL_HIDDEN_LAYER_TAG_NAMES = new Set/);
  assert.match(source, /'style'/);
  assert.match(source, /'script'/);
  assert.match(source, /NON_VISUAL_HIDDEN_LAYER_TAG_NAMES\.has\(element\.tagName\.toLowerCase\(\)\)/);
  assert.match(source, /function shouldDisplayHiddenLayerRecord\(/);
  assert.match(source, /record\.reason/);
  assert.match(source, /filter\.reasons\.includes\(record\.reason\)/);
  assert.match(source, /!filter\.includeInternal && record\.isCanvasInternal/);
  assert.match(source, /!filter\.includeDescendants && record\.hasHiddenAncestor/);
  assert.match(source, /const textQuery = filter\.textQuery\.trim\(\)\.toLowerCase\(\)/);
  assert.match(source, /const elementText = record\.element\.textContent\?\.trim\(\)\.toLowerCase\(\) \?\? ''/);
  assert.match(source, /!elementText\.includes\(textQuery\)/);
  assert.match(source, /function getPreviewZIndex\(element: HTMLElement, computedStyle: CSSStyleDeclaration\)/);
  assert.match(source, /const parsedZIndex = Number\.parseInt\(computedStyle\.zIndex, 10\)/);
  assert.match(source, /return Math\.max\(baseZIndex, 1000 \+ depth\)/);
  assert.match(source, /function getHiddenLayerPreviewDisplay\(element: HTMLElement, style: CSSStyleDeclaration\)/);
  assert.match(source, /style\.justifyContent !== 'normal'/);
  assert.match(source, /style\.alignItems !== 'normal'/);
  assert.match(source, /element\.style\.setProperty\('display', getHiddenLayerPreviewDisplay\(element, computedStyle\), 'important'\)/);
  assert.match(source, /if \(computedStyle\.opacity === '0'\) \{/);
  assert.match(source, /element\.style\.setProperty\('opacity', computedStyle\.opacity, 'important'\)/);
  assert.match(source, /if \(rect\.width <= 0\) \{/);
  assert.match(source, /element\.style\.removeProperty\('min-width'\)/);
  assert.match(source, /if \(rect\.height <= 0\) \{/);
  assert.match(source, /element\.style\.removeProperty\('min-height'\)/);
  assert.match(source, /element\.style\.setProperty\('z-index', String\(getPreviewZIndex\(element, computedStyle\)\), 'important'\)/);
  assert.match(source, /const shouldReposition = isElementCompletelyOutsideViewport/);
  assert.match(source, /if \(shouldReposition\) \{/);
  assert.match(source, /element\.style\.setProperty\('position', 'relative', 'important'\)/);
  assert.match(source, /element\.style\.removeProperty\('position'\)/);
  assert.match(source, /const visitedElements = new Set<HTMLElement>\(\)/);
  assert.match(source, /function isCanvasInternalElement\(element: HTMLElement\)/);
  assert.match(source, /split\(\/\\s\+\/\)/);
  assert.match(source, /classToken\.startsWith\('gjs-'\)/);
  assert.match(source, /canvasDocument\.body\.querySelectorAll<HTMLElement>\('\*'\)\.forEach/);
  assert.match(source, /const componentByElement = new Map<HTMLElement, any>\(\)/);
  assert.match(source, /const hiddenLayerRecords: HiddenLayerRecord\[] = \[\]/);
  assert.match(source, /const previewedElements: HTMLElement\[] = \[\]/);
  assert.match(source, /const hasNestedPreview = Boolean\(\s*element\.querySelector\(`\[\$\{HIDDEN_LAYER_PREVIEW_ATTRIBUTE\}\]`\),\s*\)/);
  assert.match(source, /element\.setAttribute\(HIDDEN_LAYER_PASS_THROUGH_ATTRIBUTE, 'true'\)/);
  assert.match(source, /selectable: false/);
  assert.match(source, /hoverable: false/);
  assert.match(source, /hiddenLayerCountsByReason/);
  assert.doesNotMatch(source, /\[\$\{HIDDEN_LAYER_PREVIEW_ATTRIBUTE\}\] \{\s*display: block !important;/);
  assert.doesNotMatch(source, /\[\$\{HIDDEN_LAYER_PREVIEW_ATTRIBUTE\}\] \{\s*[\s\S]*position: relative !important;/);
  assert.match(source, /applyTemporaryHiddenLayerStyle/);
  assert.match(source, /restoreTemporaryHiddenLayerStyle/);
  assert.match(source, /element\.removeAttribute\(HIDDEN_LAYER_PASS_THROUGH_ATTRIBUTE\)/);
  assert.match(source, /function isCanvasHTMLElement/);
  assert.match(source, /value instanceof canvasWindow\.HTMLElement/);
  assert.match(source, /value\.ownerDocument === canvasDocument/);
  assert.match(source, /isNonVisualEditableElement/);
  assert.match(source, /getComputedStyle/);
  assert.match(source, /getBoundingClientRect/);
  assert.match(source, /display === 'none'/);
  assert.match(source, /visibility === 'hidden'/);
  assert.match(source, /opacity === '0'/);
  assert.match(source, /position === 'absolute' \|\| position === 'fixed'/);
  assert.match(source, /pointer-events: auto !important/);
  assert.match(source, /\[\$\{HIDDEN_LAYER_PASS_THROUGH_ATTRIBUTE\}\] \{\s*pointer-events: none !important;/);
  assert.doesNotMatch(source, /background-color: rgba\(255, 251, 235, 0\.92\) !important/);
});

test('VisualCanvasPane performance diagnostics stay behind a debug gate', async () => {
  const source = await readFile(new URL('./VisualCanvasPane.tsx', import.meta.url), 'utf8');

  assert.match(source, /CCUI_DEBUG_VISUAL_CANVAS_PERF/);
  assert.match(source, /function isCanvasPerfDebugEnabled\(\)/);
  assert.match(source, /function collectCanvasHeadDebugSummary\(/);
  assert.match(source, /logCanvasPerf\('head-sync-scheduled'/);
  assert.match(source, /logCanvasPerf\('head-sync-missing-document'/);
  assert.match(source, /logCanvasPerf\('canvas-frame-load-event'/);
  assert.match(source, /logCanvasPerf\('canvas-frame-load-body-event'/);
  assert.match(source, /readyState: canvasDocument\?\.readyState \?\? null/);
  assert.match(source, /hasHead: Boolean\(canvasDocument\?\.head\)/);
  assert.match(source, /hasBody: Boolean\(canvasDocument\?\.body\)/);
  assert.match(source, /baseURI: canvasDocument\.baseURI/);
  assert.match(source, /headChildCount:/);
  assert.match(source, /assetUrls:/);
  assert.match(source, /styleTagCount:/);
  assert.match(source, /scriptTagCount:/);
  assert.match(source, /managedHeadNodeCount:/);
  assert.match(source, /if \(!isCanvasPerfDebugEnabled\(\)\) \{\s*return;\s*\}/);
  assert.match(source, /logCanvasPerf\('prepared'/);
  assert.match(source, /logCanvasPerf\('components'/);
  assert.match(source, /logCanvasPerf\('head-sync'/);
  assert.match(source, /logCanvasPerf\('head-state'/);
});

test('VisualCanvasPane source separates design and source toolbar states', async () => {
  const source = await readFile(new URL('./VisualCanvasPane.tsx', import.meta.url), 'utf8');

  assert.doesNotMatch(source, /ccui-switch-source/);
  assert.doesNotMatch(source, /ccui-switch-design/);
  assert.doesNotMatch(source, /ccui-reload/);
  assert.doesNotMatch(source, /ccui-save/);
});

test('VisualCanvasPane source wires official-style Basic and Forms block registries', async () => {
  const source = await readFile(new URL('./VisualCanvasPane.tsx', import.meta.url), 'utf8');

  assert.match(source, /registerVisualHtmlComponentTypes\(editorInstance\)/);
  assert.match(source, /registerVisualHtmlBlocks\(editorInstance\)/);
});
