import test from 'node:test';
import assert from 'node:assert/strict';

import {
  mergeHistoricalChatMessages,
  projectHistoricalChatMessages,
} from './projectHistoricalChatMessages.ts';

test('projectHistoricalChatMessages projects canonical user, assistant, thinking, error and compact messages for legacy pane', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'u1',
      sessionId: 'sess-1',
      role: 'user',
      text: '继续执行',
      timestamp: '2026-04-23T10:00:00.000Z',
      kind: 'text',
    },
    {
      id: 't1',
      sessionId: 'sess-1',
      role: 'assistant',
      text: '分析中',
      timestamp: '2026-04-23T10:00:01.000Z',
      kind: 'thinking',
    },
    {
      id: 'c1',
      sessionId: 'sess-1',
      role: 'tool',
      text: null,
      timestamp: '2026-04-23T10:00:02.000Z',
      kind: 'compact_boundary',
    },
    {
      id: 'e1',
      sessionId: 'sess-1',
      role: 'tool',
      text: '执行失败',
      timestamp: '2026-04-23T10:00:03.000Z',
      kind: 'error',
    },
    {
      id: 'a1',
      sessionId: 'sess-1',
      role: 'assistant',
      text: '最终回答',
      timestamp: '2026-04-23T10:00:04.000Z',
      kind: 'text',
    },
  ]);

  assert.deepEqual(
    projected.map((message) => [message.id, message.type, message.normalizedKind]),
    [
      ['u1', 'user', 'text'],
      ['t1', 'assistant', 'thinking'],
      ['c1', 'assistant', 'compact_boundary'],
      ['e1', 'error', 'error'],
      ['a1', 'assistant', 'text'],
    ],
  );
});

test('projectHistoricalChatMessages does not project session_status or debug_ref as standalone legacy chat bubbles', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'status-1',
      sessionId: 'sess-1',
      role: 'tool',
      text: 'still active',
      timestamp: '2026-04-23T10:00:00.000Z',
      kind: 'session_status',
      content: { status: 'running', detail: 'still active' },
    },
    {
      id: 'debug-1',
      sessionId: 'sess-1',
      role: 'tool',
      text: null,
      timestamp: '2026-04-23T10:00:01.000Z',
      kind: 'debug_ref',
      content: { label: 'sdk_debug_log#1', path: '/tmp/debug.log' },
    },
  ]);

  assert.deepEqual(projected, []);
});

test('projectHistoricalChatMessages hides raw command protocol messages from history', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'u1',
      sessionId: 'sess-1',
      role: 'user',
      text: '<command-name>/clear</command-name>\n<command-message>clear</command-message>',
      timestamp: '2026-04-23T10:00:00.000Z',
      kind: 'text',
    },
    {
      id: 'u2',
      sessionId: 'sess-1',
      role: 'user',
      text: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
      timestamp: '2026-04-23T10:00:01.000Z',
      kind: 'text',
    },
    {
      id: 'a1',
      sessionId: 'sess-1',
      role: 'assistant',
      text: '正常回答',
      timestamp: '2026-04-23T10:00:02.000Z',
      kind: 'text',
    },
  ]);

  assert.deepEqual(
    projected.map((message) => [message.id, message.type, message.content]),
    [
      ['u1', 'user', '/clear'],
      ['a1', 'assistant', '正常回答'],
    ],
  );
});

test('projectHistoricalChatMessages does not project tool_result records with role=user as user chat bubbles', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'u1',
      sessionId: 'sess-1',
      role: 'user',
      text: '帮我调研一下',
      timestamp: '2026-04-23T10:00:00.000Z',
      kind: 'text',
    },
    {
      id: 'tr1',
      sessionId: 'sess-1',
      role: 'user',
      text: '由于网络工具暂时无法使用，我将基于已有知识为您整理佛山市天气与气候调研报告。',
      timestamp: '2026-04-23T10:00:05.000Z',
      kind: 'tool_result',
      type: 'tool_result',
    },
  ]);

  assert.deepEqual(
    projected.map((message) => [message.id, message.type, message.content]),
    [
      ['u1', 'user', '帮我调研一下'],
    ],
  );
});

test('projectHistoricalChatMessages ignores queue-operation transcript noise so user input is not projected twice', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'user-1',
      sessionId: 'sess-queue',
      role: 'user',
      text: '321',
      timestamp: '2026-04-26T02:00:00.000Z',
      kind: 'text',
      type: 'message',
    },
    {
      id: 'queue-1',
      sessionId: 'sess-queue',
      role: 'queue-operation',
      text: '321',
      timestamp: '2026-04-26T02:00:00.500Z',
      kind: 'text',
      type: 'message',
    },
    {
      id: 'assistant-1',
      sessionId: 'sess-queue',
      role: 'assistant',
      text: '收到 321',
      timestamp: '2026-04-26T02:00:02.000Z',
      kind: 'text',
      type: 'message',
    },
  ]);

  assert.deepEqual(
    projected.map((message) => [message.id, message.type, message.content]),
    [
      ['user-1', 'user', '321'],
      ['assistant-1', 'assistant', '收到 321'],
    ],
  );
});

test('projectHistoricalChatMessages hides expanded skill prompt user records', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'u1',
      sessionId: 'sess-1',
      role: 'user',
      text: "/graphify query 'IT资产报废'",
      timestamp: '2026-04-23T11:59:00.000Z',
      kind: 'text',
    },
    {
      id: 'u2',
      sessionId: 'sess-1',
      role: 'user',
      text: `Base directory for this skill: /Users/zhanglt21/.claude/skills/graphify

# graphify

Turn any folder into a graph.`,
      timestamp: '2026-04-23T11:59:01.000Z',
      kind: 'text',
    },
  ]);

  assert.deepEqual(
    projected.map((message) => [message.id, message.type, message.content]),
    [
      ['u1', 'user', "/graphify query 'IT资产报废'"],
    ],
  );
});

test('projectHistoricalChatMessages hides expanded skill prompt user records without requiring a nearby slash command', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'u-expanded',
      sessionId: 'sess-1',
      role: 'user',
      text: `Base directory for this skill: /Users/zhanglt21/.claude/skills/gen-image

# gen-image

Internal skill prompt body.`,
      timestamp: '2026-04-23T12:00:00.000Z',
      kind: 'text',
    },
    {
      id: 'a1',
      sessionId: 'sess-1',
      role: 'assistant',
      text: '我会继续处理图片生成。',
      timestamp: '2026-04-23T12:00:01.000Z',
      kind: 'text',
    },
  ]);

  assert.deepEqual(
    projected.map((message) => [message.id, message.type, message.content]),
    [
      ['a1', 'assistant', '我会继续处理图片生成。'],
    ],
  );
});

test('projectHistoricalChatMessages projects historical user images as real image data when base64 is available', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'u-image',
      sessionId: 'sess-image',
      role: 'user',
      text: '看这张图',
      timestamp: '2026-04-26T03:00:00.000Z',
      kind: 'text',
      content: [
        { type: 'text', text: '看这张图' },
        {
          type: 'image',
          source: {
            type: 'base64',
            media_type: 'image/png',
            data: 'ZmFrZS1wbmctZGF0YQ==',
          },
        },
      ],
    },
  ]);

  assert.equal(projected.length, 1);
  assert.equal(projected[0].type, 'user');
  assert.equal(projected[0].content, '看这张图');
  assert.deepEqual(projected[0].images, [
    {
      data: 'data:image/png;base64,ZmFrZS1wbmctZGF0YQ==',
      name: 'image-1.png',
      mimeType: 'image/png',
    },
  ]);
});

test('projectHistoricalChatMessages keeps image-only historical user messages and falls back to placeholders when binary is unavailable', () => {
  const projected = projectHistoricalChatMessages([
    {
      id: 'u-image-placeholder',
      sessionId: 'sess-image',
      role: 'user',
      text: null,
      timestamp: '2026-04-26T03:05:00.000Z',
      kind: 'text',
      content: [
        {
          type: 'image',
          source: {
            type: 'file',
            media_type: 'image/png',
          },
        },
      ],
    },
  ]);

  assert.equal(projected.length, 1);
  assert.equal(projected[0].type, 'user');
  assert.equal(projected[0].content, '');
  assert.deepEqual(projected[0].images, [
    {
      data: null,
      name: 'image-1.png',
      mimeType: 'image/png',
      isPlaceholder: true,
      placeholderLabel: '已发送图片',
    },
  ]);
});

test('mergeHistoricalChatMessages dedupes pending local user echoes once canonical history catches up', () => {
  const merged = mergeHistoricalChatMessages(
    [{
      id: 'u1',
      messageId: 'u1',
      type: 'user',
      content: '请继续',
      timestamp: '2026-04-23T10:00:00.000Z',
      normalizedKind: 'text',
    }],
    [
      {
        id: 'local_1',
        type: 'user',
        content: '请继续',
        timestamp: '2026-04-23T10:00:02.000Z',
        normalizedKind: 'text',
      },
      {
        id: 'local_2',
        type: 'error',
        content: '本地错误提示',
        timestamp: '2026-04-23T10:00:03.000Z',
        normalizedKind: 'error',
      },
    ],
  );

  assert.deepEqual(
    merged.map((message) => [message.id, message.type, message.content]),
    [
      ['u1', 'user', '请继续'],
      ['local_2', 'error', '本地错误提示'],
    ],
  );
});

test('mergeHistoricalChatMessages drops expanded skill prompt echoes when canonical history already has the raw slash input', () => {
  const merged = mergeHistoricalChatMessages(
    [{
      id: 'u1',
      messageId: 'u1',
      type: 'user',
      content: "/graphify query 'IT设备管理中IT资产报废申请选择设备明细'",
      timestamp: '2026-04-23T11:59:00.000Z',
      normalizedKind: 'text',
    }],
    [{
      id: 'local-skill-1',
      type: 'user',
      content: `Base directory for this skill: /Users/zhanglt21/.claude/skills/graphify

# graphify

Turn any folder of files into a navigable knowledge graph with community detection, an honest audit trail, and three outputs: interactive HTML, GraphRAG-ready JSON, and a plain-language GRAPH_REPORT.md.`,
      timestamp: '2026-04-23T11:59:01.000Z',
      normalizedKind: 'text',
    }],
  );

  assert.deepEqual(
    merged.map((message) => [message.id, message.type, message.content]),
    [
      ['u1', 'user', "/graphify query 'IT设备管理中IT资产报废申请选择设备明细'"],
    ],
  );
});

test('mergeHistoricalChatMessages dedupes pending local assistant echoes once canonical history catches up', () => {
  const merged = mergeHistoricalChatMessages(
    [{
      id: 'u1',
      messageId: 'u1',
      type: 'user',
      content: '321',
      timestamp: '2026-04-26T02:00:00.000Z',
      normalizedKind: 'text',
    }, {
      id: 'a1',
      messageId: 'a1',
      type: 'assistant',
      content: '收到 321',
      timestamp: '2026-04-26T02:00:02.000Z',
      normalizedKind: 'text',
    }],
    [{
      id: 'local-assistant-1',
      type: 'assistant',
      content: '收到 321',
      timestamp: '2026-04-26T02:00:02.500Z',
      normalizedKind: 'text',
    }, {
      id: 'local-user-2',
      type: 'user',
      content: '下一条',
      timestamp: '2026-04-26T02:01:00.000Z',
      normalizedKind: 'text',
    }],
  );

  assert.deepEqual(
    merged.map((message) => [message.id, message.type, message.content]),
    [
      ['u1', 'user', '321'],
      ['a1', 'assistant', '收到 321'],
      ['local-user-2', 'user', '下一条'],
    ],
  );
});
